django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("to_do_list.urls")),
]

to_do_list/urls.py
from django.urls import path
from .views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
)

urlpatterns = [
    path("task/new/", TaskCreateView.as_view(), name="task_new"),
    path("task/<int:pk>/", TaskDetailView.as_view(), name="task_detail"),
    path("task/<int:pk>/edit/", TaskUpdateView.as_view(), name="task_edit"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task_delete"),
    path("", TaskListView.as_view(), name="home"),
]

to_do_list/models.py
from django.db import models
from django.urls import reverse


class Task(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE,)
    body = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("task_detail", kwargs={"pk": self.pk})

to_do_list/views.py
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Task


class TaskListView(ListView):
    model = Task
    template_name = "home.html"


class TaskDetailView(DetailView):
    model = Task
    template_name = "task_detail.html"


class TaskCreateView(CreateView):
    model = Task
    template_name = "task_new.html"
    fields = ["title", "author", "body"]


class TaskUpdateView(UpdateView):
    model = Task
    template_name = "task_edit.html"
    fields = ["title", "body"]


class TaskDeleteView(DeleteView):
    model = Task
    template_name = "task_delete.html"
    success_url = reverse_lazy("home")

templates/base.html
<html>
    <head>
        <title>To Do List</title>
    </head>
    <body>
        <header>
            <h1><a ref="{% url 'home' %}">To Do List</a></h1>
            <a href="{% url 'task_new' %}">+ New Task</a>
        </header>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
{% for task in task_list %}
    <div class="task-entry">
        <h2><a href="{% url 'task_detail' task.pk %}">{{ task.title }}</a></h2>
        <p>{{ task.body }}</p>
    </div>
{% endfor %}
{% endblock content %}

templates/task_delete.html
{% block content %}
<h1>Delete Task</h1> <a href="{% url 'home' %}">Back to the list</a>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task.title }}"?</p>
    <input type="submit" value="Yes">
</form>
{% endblock content %}

templates/task_detail.html
{% block content %}
<div class="task-entry">
    <h1>{{ task.title }}</h1> <a href="{% url 'home' %}">Back to the list</a>
    <p>{{ task.body }}</p>
</div>

<p><a href="{% url 'task_edit' task.pk %}">Edit Task</a></p>
<p><a href="{% url 'task_delete' task.pk %}">Delete Task</a></p>
{% endblock content %}

templates/task_edit.html
{% block content %}
<h1>Edit Task</h1> <a href="{% url 'home' %}">Back to the list</a>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock content %}

templates/task_new.html
{% block content %}
<h1>New Task</h1> <a href="{% url 'home' %}">Back to the list</a>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}